version: '3.9'

services:
  db_api_todo:
    container_name: db_api_todo
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_api_todo
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

  app_api_todo:
    container_name: app_api_todo
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db_api_todo

volumes:
  pg-data:
