version: '3.9'

services:
  db_api_todo:
    container_name: db_api_todo
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_api_todo
    ports:
      - 5432:5432
    volumes:
      - ./db_api_todo:/var/lib/postgresql/data
  app_api_todo:
    container_name: app_api_todo
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db_api_todo

volumes:
  db_api_todo:
